[package]
name = "main"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.2"

[cairo]
sierra-replace-ids = false
inlining-strategy = 2

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
