[sncast.devnet]
url = "http://localhost:5050/rpc"
accounts-file = "accounts.json"
account = "devnet0"
show-explorer-links = false

[sncast.default]
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_8"
account = "test"
